
#$Id: Makefile.0,v 1.3 1992/11/11 13:58:11 berg Exp $

all: $(MANSS)

make:
	@$(SHELL) -c "exit 0"

../new:
	@-mkdir $@ 2>$(DEVNULL); exit 0

man.sed: man_sed

man_sed:
	cd ../src; $(MAKE) ../man/man.sed

clean:
	$(RM) $(MANSS) man.sed _Makefile core

Makefile: ../Makefile Makefile.0
	@echo "You have made changes to the master Makefile, in order for"
	@echo "these changes to show through, you will have to do first:"
	@echo "$(MAKE) makefiles"

makefiles Makefiles makefile:
	cd ..; $(MAKE) makefiles

init:
	cd ..; $(MAKE) $@
