
#$Id: Makefile.0,v 1.4 1993/02/10 19:17:47 berg Exp $

all: $(MANSS)

make:
	@$(SHELL) -c "exit 0"

../config.check:
	@cd ..; $(MAKE) config.check

man.sed: man_sed

man_sed:
	@cd ../src; $(MAKE) ../man/man.sed

clean:
	$(RM) $(MANSS) man.sed _Makefile core

Makefile: ../Makefile Makefile.0
	@echo "You have made changes to the master Makefile, in order for"
	@echo "these changes to show through, you will have to do first:"
	@echo "$(MAKE) makefiles"

makefiles Makefiles makefile:
	cd ..; $(MAKE) makefiles

init:
	cd ..; $(MAKE) $@
