#$Id: Makefile.1,v 1.14 1993/02/18 17:19:31 berg Exp $

HIDEMAKE=$(MAKE)

all: bins mans recommend

make:
	@$(SHELL) -c "exit 0"

bins: config.check src/Makefile
	cd src; $(MAKE) $(NBINS) multigram

mans: config.check man/Makefile
	cd man; $(MAKE) $(NMANS)

autoconf.h: src/Makefile src/autoconf
	cd src; $(MAKE) ../$@

procmail: config.check src/Makefile man/Makefile
	cd src; $(MAKE) ../new/$@ ../new/mailstat
	cd man; $(MAKE) ../new/$@.1 ../new/$@rc.5 ../new/$@ex.5

mailstat: procmail

formail lockfile: config.check src/Makefile man/Makefile
	cd src; $(MAKE) ../new/$@
	cd man; $(MAKE) ../new/$@.1

multigram: config.check src/Makefile man/Makefile
	cd src; $(MAKE) $@

config.check: config.h
	@echo Housekeeping file >$@
	@-mkdir new 2>$(DEVNULL); exit 0
	@-if $(FGREP) -n -e '`' config.h $(DEVNULL) | $(FGREP) -v EOFName ; \
	 then \
	 echo;echo '	^^^^^^^^^^^^^^^^^^^^ WARNING ^^^^^^^^^^^^^^^^^^^^^';\
	      echo '	* Having backquotes in there could be unhealthy! *';\
	 echo;fi;exit 0

recommend: src/Makefile
	@cd src; $(MAKE) $@ >$(DEVNULL)
	@echo ----------------------------------------------------------------\
---------------
	@if $(FGREP) CF_no_procmail_yet autoconf.h >$(DEVNULL); \
	 then echo If you are a system administrator you should consider \
integrating procmail; echo into the mail-delivery system -- for advanced \
functionality AND SECURITY --.; echo For more information about this topic \
you should look in the examples/advanced; echo file.; elif \
	 cat /usr/lib/sendmail.cf /etc/sendmail.cf 2>$(DEVNULL) | \
	 grep 'Mlocal.*procmail.*F=[a-zA-Z]*u' >$(DEVNULL) ; then \
	 echo The recommendation for the sendmail.cf entry of procmail has \
changed.; echo I suggest you remove the '`u'"'"-flag 'like in:'; echo ; \
	  sed -n 's/.*\(Mlocal.*procmail.*F=[a-zA-Z]*\)u/\1/p' `if test -f \
	 /etc/sendmail.cf; then echo /etc/sendmail.cf; else \
	 echo /usr/lib/sendmail.cf; fi`; fi
	@echo
	@echo "Also, HIGHLY RECOMMENDED (type 'make suid' to execute it):"
	@echo
	@src/$@ $(BINDIR)/procmail $(BINDIR)/lockfile >suid.sh
	@src/$@ $(BINDIR)/procmail $(BINDIR)/lockfile
	@echo ----------------------------------------------------------------\
---------------

suid.sh: recommend

suid: suid.sh install.bin
	@cat $@.sh
	@$(SHELL) ./$@.sh
	@cd $(BINDIR); echo Installed in $(BINDIR); ls -l $(BINSS)

$(MANS): mans

$(BINS): bins

install.man: $(MANS)
	@-mkdir $(MANDIR) 2>$(DEVNULL); exit 0
	@-mkdir $(MAN1DIR) 2>$(DEVNULL); exit 0
	@-mkdir $(MAN5DIR) 2>$(DEVNULL); exit 0
	@chmod 0644 $(MANS)
	@for a in $(MANS1S); \
	  do $(INSTALL) new/$$a.1 $(MAN1DIR)/$$a.$(MAN1SUFFIX); done
	@for a in $(MANS5S); \
	  do $(INSTALL) new/$$a.5 $(MAN5DIR)/$$a.$(MAN5SUFFIX); done
	@echo Housekeeping file >install.man

install.bin: $(BINS)
	@-mkdir $(BINDIR) 2>$(DEVNULL); exit 0
	@chmod 0755 $(BINS)
	$(INSTALL) $(BINS) $(BINDIR)
	@echo Housekeeping file >install.bin

install: install.man install.bin
	@echo
	@cd $(BINDIR); echo Installed in $(BINDIR); ls -l $(BINSS)
	@cd $(MAN1DIR); echo Installed in $(MAN1DIR); ls -l $(MANS1)
	@cd $(MAN5DIR); echo Installed in $(MAN5DIR); ls -l $(MANS5)
	@$(MAKE) recommend

deinstall:
	@echo ----------------------------- Deinstalling the procmail package.
	@$(RM) install.man install.bin
	@echo ----------------------------- Checking if everything was removed:
	@-cd $(BINDIR); $(RM) $(BINSS); ls -l $(BINSS); exit 0
	@-cd $(MAN1DIR); $(RM) $(MANS1); ls -l $(MANS1); exit 0
	@-cd $(MAN5DIR); $(RM) $(MANS5); ls -l $(MANS5); exit 0
	@echo ----------------------------- Ready.

clean: config.check
	-for a in $(SUBDIRS); do cd $$a; $(MAKE) $@; cd ..; done; exit 0
	$(RM) $(MANS) $(BINS) libcheck install.man install.bin suid.sh \
	 _Makefile core autoconf.h.tmp

realclean: clean _init
	$(RM) config.check
	-rmdir new; exit 0
	-for a in $(SUBDIRS); do $(MV) $$a/Makefile.init $$a/Makefile; done; \
	 exit 0

veryclean clobber: realclean

_init:
	sed -e '/^# Makefile.1 - mark/,$$ d' <Makefile >_Makefile
	cat Makefile.0 >>_Makefile
	$(MV) _Makefile Makefile
	$(RM) Makefile.0

man/Makefile: man/Makefile.0

src/Makefile: src/Makefile.0

man/Makefile src/Makefile: Makefile
	$(MAKE) _init; $(HIDEMAKE) init

Makefile: Makefile.1 initmake

init makefiles Makefiles makefile: man/Makefile src/Makefile
