#!/bin/sh
#$Id: subscreen,v 1.1 1993/11/24 19:45:57 berg Exp $

# $1 contains the mail address of the prospective subscriber
# We return zero if subscription is allowed, and one if not.

case "$1" in
  *@hostile.our.local.domain)	exit 1 ;;	# Not this one
  *@*our.local.domain)		exit 0 ;;	# This one is ok
  *@some.other.domain)		exit 0 ;;	# Ditto
esac

exit 1		# reject everything else
