
#$Id: Makefile.0,v 1.8 1992/11/12 11:38:12 berg Exp $

PM_OBJ=cstdio.$(O) common.$(O) exopen.$(O) goodies.$(O) locking.$(O) \
 mailfold.$(O) misc.$(O) pipes.$(O) regexp.$(O) robust.$(O) sublib.$(O)
LF_OBJ=exopen.$(O) sublib.$(O)
FM_OBJ=common.$(O) fields.$(O) formisc.$(O) sublib.$(O) ecommon.$(O)

all:	$(BINSS)

make:
	@$(SHELL) -c "exit 0"			# fake target

procmail: procmail.$(O) $(PM_OBJ)
	$(CC) $(CFLAGS) $@.$(O) $(PM_OBJ) -o $@ $(LDFLAGS)

lockfile: lockfile.$(O) $(LF_OBJ)
	$(CC) $(CFLAGS) $@.$(O) $(LF_OBJ) -o $@ $(LDFLAGS)

formail: formail.$(O) $(FM_OBJ)
	$(CC) $(CFLAGS) $@.$(O) $(FM_OBJ) -o $@ $(LDFLAGS)

mailstat: ../examples/mailstat
	cp ../examples/$@ .
	chmod 0755 $@

multigram: multigram.$(O) sublib.$(O) ecommon.$(O)
	$(CC) $(CFLAGS) $@.$(O) sublib.$(O) ecommon.$(O) -o $@ $(LDFLAGS)

../new:
	@-mkdir $@ 2>$(DEVNULL); exit 0

_autotst: _autotst.$(O)
	$(CC) $(CFLAGS) $@.$(O) -o $@ $(LDFLAGS)

# to fully support "make -n"
HIDEMAKE = $(MAKE)

../autoconf.h: autoconf Makefile
	$(SHELL) ./autoconf $(SHELL) "$(RM)" "$(MV)" $(USRINCLUDE) \
	 $(DEVNULL) "$(FGREP)" "$(HIDEMAKE)" $(O) $@

autoconf.h: ../autoconf.h

common.$(O): ../autoconf.h ../config.h includes.h procmail.h sublib.h robust.h
common.$(O): shell.h misc.h common.h

cstdio.$(O): ../autoconf.h ../config.h includes.h procmail.h robust.h cstdio.h
cstdio.$(O):  misc.h

ecommon.$(O): ../autoconf.h ../config.h includes.h ecommon.h

exopen.$(O): ../autoconf.h ../config.h includes.h procmail.h robust.h misc.h
exopen.$(O): exopen.h

fields.$(O): ../autoconf.h ../config.h includes.h formail.h sublib.h shell.h
fields.$(O): common.h fields.h ecommon.h formisc.h

formail.$(O): ../autoconf.h ../config.h includes.h formail.h sublib.h shell.h
formail.$(O): common.h fields.h ecommon.h formisc.h header.h

formisc.$(O): ../autoconf.h ../config.h includes.h formail.h sublib.h shell.h
formisc.$(O): common.h ecommon.h formisc.h

goodies.$(O): ../autoconf.h ../config.h includes.h procmail.h sublib.h robust.h
goodies.$(O): shell.h misc.h pipes.h common.h cstdio.h goodies.h

lockfile.$(O): ../autoconf.h ../config.h includes.h sublib.h exopen.h robust.h
lockfile.$(O): misc.h

locking.$(O): ../autoconf.h ../config.h includes.h procmail.h robust.h shell.h
locking.$(O): misc.h exopen.h locking.h

mailfold.$(O): ../autoconf.h ../config.h includes.h procmail.h sublib.h
mailfold.$(O): robust.h shell.h misc.h pipes.h common.h exopen.h locking.h
mailfold.$(O): mailfold.h network.h

manconf.$(O): ../patchlevel.h ../autoconf.h ../config.h includes.h procmail.h

misc.$(O): ../autoconf.h ../config.h includes.h procmail.h sublib.h robust.h
misc.$(O): shell.h misc.h pipes.h common.h cstdio.h exopen.h regexp.h goodies.h
misc.$(O): locking.h mailfold.h

multigram.$(O): ../autoconf.h ../config.h includes.h sublib.h shell.h ecommon.h

pipes.$(O): ../autoconf.h ../config.h includes.h procmail.h robust.h shell.h
pipes.$(O): misc.h pipes.h common.h cstdio.h goodies.h mailfold.h

procmail.$(O): ../patchlevel.h ../autoconf.h ../config.h includes.h procmail.h
procmail.$(O): sublib.h robust.h shell.h misc.h pipes.h common.h cstdio.h
procmail.$(O): exopen.h goodies.h locking.h mailfold.h

regexp.$(O): ../autoconf.h ../config.h includes.h procmail.h robust.h shell.h
regexp.$(O): regexp.h

robust.$(O): ../autoconf.h ../config.h includes.h procmail.h robust.h shell.h
robust.$(O): misc.h mailfold.h shell.h

sublib.$(O): ../autoconf.h ../config.h includes.h sublib.h shell.h

recommend.$(O): ../autoconf.h ../config.h includes.h
	@$(CC) -c $(CFLAGS) $*.c

.c.$(O):
	$(CC) -c $(CFLAGS) $<

recommend: recommend.$(O) sublib.$(O)
	@$(CC) $(CFLAGS) $@.$(O) sublib.$(O) -o $@ $(LDFLAGS)

../man/man.sed: manconf.c ../autoconf.h ../config.h includes.h procmail.h
../man/man.sed: ../patchlevel.h
	$(CC) $(CFLAGS) -o _autotst manconf.c $(LDFLAGS)
	./_autotst >$@
	$(RM) _autotst

clean:
	$(RM) procmail.$(O) $(PM_OBJ) lockfile.$(O) $(LF_OBJ) formail.$O \
	 $(FM_OBJ) multigram.$(O) $(BINSS) multigram ../autoconf.h _autotst* \
	 lookfor _locktst* grepfor recommend recommend.$(O) manconf _Makefile \
	 lock.log core

Makefile: ../Makefile Makefile.0
	@echo "You have made changes to the master Makefile, in order for"
	@echo "these changes to show through, you will have to do first:"
	@echo "$(MAKE) makefiles"

makefiles Makefiles makefile:
	cd ..; $(MAKE) makefiles

init:
	cd ..; $(MAKE) $@
